# Exceptions.py

class InvalidOpcodeError:
    class InvalidFlags(Exception): ...
    
    class UnknownOpcode(Exception): ...
    
    class SomethingElse(Exception): ...

    
class InvalidMemoryWrite(Exception): ...

class InvalidRegister(Exception): ...

class UnknownError(Exception): ...

